### ISSUE TITLE
please check 

### ISSUE THREAD

**Issue by AlwaysReVaule** [getmimo/coding-challenge#6]
https://github.com/discourse/discourse-air/pull/15#issue-1239642028
@littleStudent @hz3k @flagbug @AlexGrafl @simerlec

**Comment by flagbug** [comment]
Hey @AlwaysReVaule , please use the report button on the top right of the lesson view to report issues with our content, or shoot us an email at support@getmimo.com, thanks!

**Comment by AlwaysReVaule** [comment]
@flagbug I see, I will. many thanks.
